### ISSUE TITLE
Getting a babysitter

### ISSUE THREAD

**Issue by dmil** [code4policy/2024-b0-babysitting-project#1]
As an anxious parent, I want a place to get a trusted babysitter, so that I can go out in peace

- [ ] I
- [ ] N
- [ ] V
- [ ] E
- [ ] S
- [ ] T

**Definition of Done**

**Comment by dmil** [comment]
i got 3 babysitters but need to contact some folks about two more

**Comment by dmil** [comment]
**Tasks**

- [ ] find some babysitters
- [ ] make sure they're trusted (people we know)
- [ ] put their contact info on the website
